### ISSUE TITLE
Missing doc.go

### ISSUE THREAD

**Issue by nickpresta** [mdlayher/goat#10]
You're missing a doc.go file, which includes documentation for working with your package.

See something like [sqlite3](http://godoc.org/code.google.com/p/go-sqlite/go1/sqlite3) and how they wrote their [doc.go](https://code.google.com/p/go-sqlite/source/browse/go1/sqlite3/doc.go) file.

**Comment by mdlayher** [comment]
Neat, so that is how godocs are generated.  I'll start working on that in the next couple of days.

**Comment by mdlayher** [comment]
Done, and will continue to work on it in the next few days.
