### ISSUE TITLE
Make package compatible with "go get" and remove Makefile.

### ISSUE THREAD

**Issue by ChimeraCoder** [mdlayher/goat#11]
I saw your project over on [/r/golang](http://www.reddit.com/r/golang/comments/1ueo1n/goat_bittorrent_tracker_implemention_written_in_go/) and that you were looking for feedback. Hopefully this helps.

I'm excited to play around with this, but what's standing in my way is that I cannot install or run it!

A Go project should be installable using "go get" - in this case, this means that executing the command `github.com/mdlayher/goat` should download the project, fetch all dependencies of the project, compile the project, and install the binary to `$GOPATH/bin`.

This project is incompatible with `go get` for a few reasons.
1. Files are in a `src` directory. This is unnecessary (and harmful) in Go; all files in a package should be in the same folder, and in this case, it should be the toplevel folder The folder should be named "src" only if you want the binary to be called "src", which I don't think you want.
2. The Makefile is an antipattern in Go. There is nothing that the Makefile does here that is not already provided by the standard Go tools, and you should use those instead. As it is written, your Makefile actually will not execute properly on all systems that Go supports, whereas the standard Go build tools will handle this correctly.

**Comment by ChimeraCoder** [comment]
I had a couple of minutes to spare, so I just submitted a pull request. I tested that it compiles and seems to run (though there aren't any test files for the project that I could check it against).

Let me know if you have any questions.

**Comment by mdlayher** [comment]
Thanks for your help! Still trying to get the hang of managing things with the go tools, but it is certainly apparent that they were designed to work in a very specific way.
