### ISSUE TITLE
Timing-attack resistant string comparison implementation

### ISSUE THREAD

**Issue by toqueteos** [mdlayher/goat#27]
You should operate on runes instead of using string indices (unicode/utf8 pkg to the rescue) or instead use `[]byte` which can be compared easily with
http://golang.org/pkg/crypto/subtle/#ConstantTimeCompare

Go does provide A LOT of good stuff to use on the std libraries.

Example problem: http://play.golang.org/p/MrX6ZXZkLD

EDIT: You seem to be using this function to compare hashes, what's wrong with `bytes.Equal` or just `subtle.ConstantTimeCompare`?

**Comment by mdlayher** [comment]
That's really cool that constant time comparisons are built in to the standard library. I had no idea, but will definitely replace my implementation with the standard one. Thanks for the feedback!

**Comment by toqueteos** [comment]
You are welcome, I'm using your project as learning material. I've always found interesting torrent trackers and this is helping a lot. So thanks to you!

**Comment by mdlayher** [comment]
Fixed, as of 8912aecafa6b11a20a6e186a52554f4513a0375a.  Thanks again for your suggestion.  I'm considering drafting up a bunch of documentation on what I've learned about torrent trackers.  Feel free to contact me if you have any more questions!
