### ISSUE TITLE
Implement DbHandler interface, implement MapDb

### ISSUE THREAD

**Issue by mdlayher** [mdlayher/goat#4]
Create storage interface using best practices for Go, and make it generic enough so that any number of backends can be used with it.

The interface should query all available backends at once, and once a backend returns the data, the query should be halted on all others.

Implement MapDb to allow for in-program caching of data.

**Comment by mdlayher** [comment]
As discussed, we will also need the ability to append collections for announce and scrape logs.

**Comment by eliothedeman** [comment]
Currently writing an implementation such that write requests will check if the struct being written is a log, and if so, appends to the log
